# Generated by Django 4.2.8 on 2024-02-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
