# Generated by Django 5.0.4 on 2024-06-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_profile_old_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
