# Generated by Django 4.2.8 on 2024-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="shipping_address2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
