# Generated by Django 5.0.4 on 2024-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_alter_shippingaddress_shipping_address2"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="shipping_address2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
