# Generated by Django 5.0.4 on 2024-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_order_shipped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
